export const PHONE_BRANDS = ["iPhone", "Samsung", "Xiaomi", "Oppo"] as const;
export type PhoneBrand = (typeof PHONE_BRANDS)[number];

export const PHONE_MODELS: Record<PhoneBrand, string[]> = {
  iPhone: [
    "iPhone 18 Pro Max",
    "iPhone 18 Pro",
    "iPhone 17 Pro Max",
    "iPhone 17 Pro",
    "iPhone 17 Air",
    "iPhone 17",
    "iPhone 16 Pro Max",
    "iPhone 16 Pro",
    "iPhone 16 Plus",
    "iPhone 16",
    "iPhone 15 Pro Max",
    "iPhone 15 Pro",
    "iPhone 15 Plus",
    "iPhone 15",
    "iPhone 14 Pro Max",
    "iPhone 14 Pro",
    "iPhone 14 Plus",
    "iPhone 14",
    "iPhone 13 Pro Max",
    "iPhone 13 Pro",
    "iPhone 13",
    "iPhone 13 mini",
    "iPhone 12 Pro Max",
    "iPhone 12 Pro",
    "iPhone 12",
    "iPhone 12 mini",
  ],
  Samsung: [
    "Galaxy S26 Ultra",
    "Galaxy S26+",
    "Galaxy S26",
    "Galaxy S25 Ultra",
    "Galaxy S25+",
    "Galaxy S25 Edge",
    "Galaxy S25 FE",
    "Galaxy S25",
    "Galaxy S24 Ultra",
    "Galaxy S24+",
    "Galaxy S24 FE",
    "Galaxy S24",
    "Galaxy S23 Ultra",
    "Galaxy S23+",
    "Galaxy S23 FE",
    "Galaxy S23",
    "Galaxy S22 Ultra",
    "Galaxy S22+",
    "Galaxy S22",
    "Galaxy S21 FE",
    "Galaxy Z Flip 7",
    "Galaxy Z Fold 7",
    "Galaxy Z Flip 6",
    "Galaxy Z Fold 6",
    "Galaxy A56",
    "Galaxy A55",
    "Galaxy A54",
    "Galaxy A36",
    "Galaxy A35",
    "Galaxy A34",
    "Galaxy A26",
    "Galaxy A25",
    "Galaxy A16",
    "Galaxy A15",
  ],
  Xiaomi: [
    "Xiaomi 16 Pro",
    "Xiaomi 16",
    "Xiaomi 15 Ultra",
    "Xiaomi 15 Pro",
    "Xiaomi 15",
    "Xiaomi 14 Ultra",
    "Xiaomi 14 Pro",
    "Xiaomi 14T Pro",
    "Xiaomi 14T",
    "Xiaomi 14",
    "Xiaomi 13T Pro",
    "Xiaomi 13T",
    "Xiaomi 13 Pro",
    "Xiaomi 13",
    "Redmi Note 15 Pro+",
    "Redmi Note 15 Pro",
    "Redmi Note 15",
    "Redmi Note 14 Pro+",
    "Redmi Note 14 Pro",
    "Redmi Note 14",
    "Redmi Note 13 Pro+",
    "Redmi Note 13 Pro",
    "Redmi Note 13",
    "Redmi 14C",
    "Redmi 13C",
    "Poco F7 Ultra",
    "Poco F7 Pro",
    "Poco F7",
    "Poco F6 Pro",
    "Poco F6",
    "Poco X7 Pro",
    "Poco X7",
    "Poco X6 Pro",
    "Poco X6",
    "Poco M7 Pro",
    "Poco M6 Pro",
  ],
  Oppo: [
    "Oppo Find X7 Ultra",
    "Oppo Find X7",
    "Oppo Find X6 Pro",
    "Oppo Reno 11 Pro",
    "Oppo Reno 11",
    "Oppo Reno 10 Pro",
    "Oppo Reno 10",
    "Oppo A98",
    "Oppo A78",
    "Oppo A58",
  ],
};
