/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PersonalizarRouteImport } from './routes/personalizar'
import { Route as NuevaContrasenaRouteImport } from './routes/nueva-contrasena'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as MetaProductsDotcsvRouteImport } from './routes/meta-products[.]csv'
import { Route as MasVendidoRouteImport } from './routes/mas-vendido'
import { Route as FundasSublimacionRouteImport } from './routes/fundas-sublimacion'
import { Route as FundasMovilRouteImport } from './routes/fundas-movil'
import { Route as FundasRouteImport } from './routes/fundas'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccesoriosRouteImport } from './routes/accesorios'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'
import { Route as CheckoutExitoRouteImport } from './routes/checkout.exito'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe-webhook'
import { Route as AccesoriosProtectoresRouteImport } from './routes/accesorios.protectores'
import { Route as AccesoriosColgantesRouteImport } from './routes/accesorios.colgantes'
import { Route as AccesoriosCargadoresRouteImport } from './routes/accesorios.cargadores'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminStockFundasRouteImport } from './routes/_authenticated/admin.stock-fundas'
import { Route as AuthenticatedAdminProductosRouteImport } from './routes/_authenticated/admin.productos'
import { Route as AuthenticatedAdminPedidosRouteImport } from './routes/_authenticated/admin.pedidos'
import { Route as AuthenticatedAdminCuentaRouteImport } from './routes/_authenticated/admin.cuenta'
import { Route as AuthenticatedAdminContenidoRouteImport } from './routes/_authenticated/admin.contenido'
import { Route as AuthenticatedAdminCategoriasRouteImport } from './routes/_authenticated/admin.categorias'
import { Route as AuthenticatedAdminCarruselRouteImport } from './routes/_authenticated/admin.carrusel'
import { Route as AuthenticatedAdminAjustesRouteImport } from './routes/_authenticated/admin.ajustes'

const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalizarRoute = PersonalizarRouteImport.update({
  id: '/personalizar',
  path: '/personalizar',
  getParentRoute: () => rootRouteImport,
} as any)
const NuevaContrasenaRoute = NuevaContrasenaRouteImport.update({
  id: '/nueva-contrasena',
  path: '/nueva-contrasena',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MetaProductsDotcsvRoute = MetaProductsDotcsvRouteImport.update({
  id: '/meta-products.csv',
  path: '/meta-products.csv',
  getParentRoute: () => rootRouteImport,
} as any)
const MasVendidoRoute = MasVendidoRouteImport.update({
  id: '/mas-vendido',
  path: '/mas-vendido',
  getParentRoute: () => rootRouteImport,
} as any)
const FundasSublimacionRoute = FundasSublimacionRouteImport.update({
  id: '/fundas-sublimacion',
  path: '/fundas-sublimacion',
  getParentRoute: () => rootRouteImport,
} as any)
const FundasMovilRoute = FundasMovilRouteImport.update({
  id: '/fundas-movil',
  path: '/fundas-movil',
  getParentRoute: () => rootRouteImport,
} as any)
const FundasRoute = FundasRouteImport.update({
  id: '/fundas',
  path: '/fundas',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosRoute = AccesoriosRouteImport.update({
  id: '/accesorios',
  path: '/accesorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutExitoRoute = CheckoutExitoRouteImport.update({
  id: '/checkout/exito',
  path: '/checkout/exito',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe-webhook',
  path: '/api/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AccesoriosProtectoresRoute = AccesoriosProtectoresRouteImport.update({
  id: '/protectores',
  path: '/protectores',
  getParentRoute: () => AccesoriosRoute,
} as any)
const AccesoriosColgantesRoute = AccesoriosColgantesRouteImport.update({
  id: '/colgantes',
  path: '/colgantes',
  getParentRoute: () => AccesoriosRoute,
} as any)
const AccesoriosCargadoresRoute = AccesoriosCargadoresRouteImport.update({
  id: '/cargadores',
  path: '/cargadores',
  getParentRoute: () => AccesoriosRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStockFundasRoute =
  AuthenticatedAdminStockFundasRouteImport.update({
    id: '/stock-fundas',
    path: '/stock-fundas',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductosRoute =
  AuthenticatedAdminProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPedidosRoute =
  AuthenticatedAdminPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCuentaRoute =
  AuthenticatedAdminCuentaRouteImport.update({
    id: '/cuenta',
    path: '/cuenta',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminContenidoRoute =
  AuthenticatedAdminContenidoRouteImport.update({
    id: '/contenido',
    path: '/contenido',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCategoriasRoute =
  AuthenticatedAdminCategoriasRouteImport.update({
    id: '/categorias',
    path: '/categorias',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCarruselRoute =
  AuthenticatedAdminCarruselRouteImport.update({
    id: '/carrusel',
    path: '/carrusel',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAjustesRoute =
  AuthenticatedAdminAjustesRouteImport.update({
    id: '/ajustes',
    path: '/ajustes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/fundas': typeof FundasRoute
  '/fundas-movil': typeof FundasMovilRoute
  '/fundas-sublimacion': typeof FundasSublimacionRoute
  '/mas-vendido': typeof MasVendidoRoute
  '/meta-products.csv': typeof MetaProductsDotcsvRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/nueva-contrasena': typeof NuevaContrasenaRoute
  '/personalizar': typeof PersonalizarRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/accesorios/cargadores': typeof AccesoriosCargadoresRoute
  '/accesorios/colgantes': typeof AccesoriosColgantesRoute
  '/accesorios/protectores': typeof AccesoriosProtectoresRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/exito': typeof CheckoutExitoRoute
  '/product/$handle': typeof ProductHandleRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/carrusel': typeof AuthenticatedAdminCarruselRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/cuenta': typeof AuthenticatedAdminCuentaRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/stock-fundas': typeof AuthenticatedAdminStockFundasRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accesorios': typeof AccesoriosRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/fundas': typeof FundasRoute
  '/fundas-movil': typeof FundasMovilRoute
  '/fundas-sublimacion': typeof FundasSublimacionRoute
  '/mas-vendido': typeof MasVendidoRoute
  '/meta-products.csv': typeof MetaProductsDotcsvRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/nueva-contrasena': typeof NuevaContrasenaRoute
  '/personalizar': typeof PersonalizarRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/accesorios/cargadores': typeof AccesoriosCargadoresRoute
  '/accesorios/colgantes': typeof AccesoriosColgantesRoute
  '/accesorios/protectores': typeof AccesoriosProtectoresRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/exito': typeof CheckoutExitoRoute
  '/product/$handle': typeof ProductHandleRoute
  '/checkout': typeof CheckoutIndexRoute
  '/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/admin/carrusel': typeof AuthenticatedAdminCarruselRoute
  '/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/admin/cuenta': typeof AuthenticatedAdminCuentaRoute
  '/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/admin/stock-fundas': typeof AuthenticatedAdminStockFundasRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accesorios': typeof AccesoriosRouteWithChildren
  '/auth': typeof AuthRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/fundas': typeof FundasRoute
  '/fundas-movil': typeof FundasMovilRoute
  '/fundas-sublimacion': typeof FundasSublimacionRoute
  '/mas-vendido': typeof MasVendidoRoute
  '/meta-products.csv': typeof MetaProductsDotcsvRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/nueva-contrasena': typeof NuevaContrasenaRoute
  '/personalizar': typeof PersonalizarRoute
  '/privacidad': typeof PrivacidadRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terminos': typeof TerminosRoute
  '/tienda': typeof TiendaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/accesorios/cargadores': typeof AccesoriosCargadoresRoute
  '/accesorios/colgantes': typeof AccesoriosColgantesRoute
  '/accesorios/protectores': typeof AccesoriosProtectoresRoute
  '/api/stripe-webhook': typeof ApiStripeWebhookRoute
  '/checkout/exito': typeof CheckoutExitoRoute
  '/product/$handle': typeof ProductHandleRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/_authenticated/admin/ajustes': typeof AuthenticatedAdminAjustesRoute
  '/_authenticated/admin/carrusel': typeof AuthenticatedAdminCarruselRoute
  '/_authenticated/admin/categorias': typeof AuthenticatedAdminCategoriasRoute
  '/_authenticated/admin/contenido': typeof AuthenticatedAdminContenidoRoute
  '/_authenticated/admin/cuenta': typeof AuthenticatedAdminCuentaRoute
  '/_authenticated/admin/pedidos': typeof AuthenticatedAdminPedidosRoute
  '/_authenticated/admin/productos': typeof AuthenticatedAdminProductosRoute
  '/_authenticated/admin/stock-fundas': typeof AuthenticatedAdminStockFundasRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accesorios'
    | '/auth'
    | '/contacto'
    | '/favoritos'
    | '/fundas'
    | '/fundas-movil'
    | '/fundas-sublimacion'
    | '/mas-vendido'
    | '/meta-products.csv'
    | '/mis-pedidos'
    | '/nueva-contrasena'
    | '/personalizar'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/tienda'
    | '/admin'
    | '/accesorios/cargadores'
    | '/accesorios/colgantes'
    | '/accesorios/protectores'
    | '/api/stripe-webhook'
    | '/checkout/exito'
    | '/product/$handle'
    | '/checkout/'
    | '/admin/ajustes'
    | '/admin/carrusel'
    | '/admin/categorias'
    | '/admin/contenido'
    | '/admin/cuenta'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock-fundas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accesorios'
    | '/auth'
    | '/contacto'
    | '/favoritos'
    | '/fundas'
    | '/fundas-movil'
    | '/fundas-sublimacion'
    | '/mas-vendido'
    | '/meta-products.csv'
    | '/mis-pedidos'
    | '/nueva-contrasena'
    | '/personalizar'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/tienda'
    | '/accesorios/cargadores'
    | '/accesorios/colgantes'
    | '/accesorios/protectores'
    | '/api/stripe-webhook'
    | '/checkout/exito'
    | '/product/$handle'
    | '/checkout'
    | '/admin/ajustes'
    | '/admin/carrusel'
    | '/admin/categorias'
    | '/admin/contenido'
    | '/admin/cuenta'
    | '/admin/pedidos'
    | '/admin/productos'
    | '/admin/stock-fundas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accesorios'
    | '/auth'
    | '/contacto'
    | '/favoritos'
    | '/fundas'
    | '/fundas-movil'
    | '/fundas-sublimacion'
    | '/mas-vendido'
    | '/meta-products.csv'
    | '/mis-pedidos'
    | '/nueva-contrasena'
    | '/personalizar'
    | '/privacidad'
    | '/sitemap.xml'
    | '/terminos'
    | '/tienda'
    | '/_authenticated/admin'
    | '/accesorios/cargadores'
    | '/accesorios/colgantes'
    | '/accesorios/protectores'
    | '/api/stripe-webhook'
    | '/checkout/exito'
    | '/product/$handle'
    | '/checkout/'
    | '/_authenticated/admin/ajustes'
    | '/_authenticated/admin/carrusel'
    | '/_authenticated/admin/categorias'
    | '/_authenticated/admin/contenido'
    | '/_authenticated/admin/cuenta'
    | '/_authenticated/admin/pedidos'
    | '/_authenticated/admin/productos'
    | '/_authenticated/admin/stock-fundas'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AccesoriosRoute: typeof AccesoriosRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactoRoute: typeof ContactoRoute
  FavoritosRoute: typeof FavoritosRoute
  FundasRoute: typeof FundasRoute
  FundasMovilRoute: typeof FundasMovilRoute
  FundasSublimacionRoute: typeof FundasSublimacionRoute
  MasVendidoRoute: typeof MasVendidoRoute
  MetaProductsDotcsvRoute: typeof MetaProductsDotcsvRoute
  MisPedidosRoute: typeof MisPedidosRoute
  NuevaContrasenaRoute: typeof NuevaContrasenaRoute
  PersonalizarRoute: typeof PersonalizarRoute
  PrivacidadRoute: typeof PrivacidadRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TerminosRoute: typeof TerminosRoute
  TiendaRoute: typeof TiendaRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
  CheckoutExitoRoute: typeof CheckoutExitoRoute
  ProductHandleRoute: typeof ProductHandleRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personalizar': {
      id: '/personalizar'
      path: '/personalizar'
      fullPath: '/personalizar'
      preLoaderRoute: typeof PersonalizarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nueva-contrasena': {
      id: '/nueva-contrasena'
      path: '/nueva-contrasena'
      fullPath: '/nueva-contrasena'
      preLoaderRoute: typeof NuevaContrasenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meta-products.csv': {
      id: '/meta-products.csv'
      path: '/meta-products.csv'
      fullPath: '/meta-products.csv'
      preLoaderRoute: typeof MetaProductsDotcsvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas-vendido': {
      id: '/mas-vendido'
      path: '/mas-vendido'
      fullPath: '/mas-vendido'
      preLoaderRoute: typeof MasVendidoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundas-sublimacion': {
      id: '/fundas-sublimacion'
      path: '/fundas-sublimacion'
      fullPath: '/fundas-sublimacion'
      preLoaderRoute: typeof FundasSublimacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundas-movil': {
      id: '/fundas-movil'
      path: '/fundas-movil'
      fullPath: '/fundas-movil'
      preLoaderRoute: typeof FundasMovilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fundas': {
      id: '/fundas'
      path: '/fundas'
      fullPath: '/fundas'
      preLoaderRoute: typeof FundasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios': {
      id: '/accesorios'
      path: '/accesorios'
      fullPath: '/accesorios'
      preLoaderRoute: typeof AccesoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/exito': {
      id: '/checkout/exito'
      path: '/checkout/exito'
      fullPath: '/checkout/exito'
      preLoaderRoute: typeof CheckoutExitoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe-webhook': {
      id: '/api/stripe-webhook'
      path: '/api/stripe-webhook'
      fullPath: '/api/stripe-webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accesorios/protectores': {
      id: '/accesorios/protectores'
      path: '/protectores'
      fullPath: '/accesorios/protectores'
      preLoaderRoute: typeof AccesoriosProtectoresRouteImport
      parentRoute: typeof AccesoriosRoute
    }
    '/accesorios/colgantes': {
      id: '/accesorios/colgantes'
      path: '/colgantes'
      fullPath: '/accesorios/colgantes'
      preLoaderRoute: typeof AccesoriosColgantesRouteImport
      parentRoute: typeof AccesoriosRoute
    }
    '/accesorios/cargadores': {
      id: '/accesorios/cargadores'
      path: '/cargadores'
      fullPath: '/accesorios/cargadores'
      preLoaderRoute: typeof AccesoriosCargadoresRouteImport
      parentRoute: typeof AccesoriosRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stock-fundas': {
      id: '/_authenticated/admin/stock-fundas'
      path: '/stock-fundas'
      fullPath: '/admin/stock-fundas'
      preLoaderRoute: typeof AuthenticatedAdminStockFundasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/productos': {
      id: '/_authenticated/admin/productos'
      path: '/productos'
      fullPath: '/admin/productos'
      preLoaderRoute: typeof AuthenticatedAdminProductosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pedidos': {
      id: '/_authenticated/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AuthenticatedAdminPedidosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cuenta': {
      id: '/_authenticated/admin/cuenta'
      path: '/cuenta'
      fullPath: '/admin/cuenta'
      preLoaderRoute: typeof AuthenticatedAdminCuentaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/contenido': {
      id: '/_authenticated/admin/contenido'
      path: '/contenido'
      fullPath: '/admin/contenido'
      preLoaderRoute: typeof AuthenticatedAdminContenidoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/categorias': {
      id: '/_authenticated/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AuthenticatedAdminCategoriasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/carrusel': {
      id: '/_authenticated/admin/carrusel'
      path: '/carrusel'
      fullPath: '/admin/carrusel'
      preLoaderRoute: typeof AuthenticatedAdminCarruselRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ajustes': {
      id: '/_authenticated/admin/ajustes'
      path: '/ajustes'
      fullPath: '/admin/ajustes'
      preLoaderRoute: typeof AuthenticatedAdminAjustesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAjustesRoute: typeof AuthenticatedAdminAjustesRoute
  AuthenticatedAdminCarruselRoute: typeof AuthenticatedAdminCarruselRoute
  AuthenticatedAdminCategoriasRoute: typeof AuthenticatedAdminCategoriasRoute
  AuthenticatedAdminContenidoRoute: typeof AuthenticatedAdminContenidoRoute
  AuthenticatedAdminCuentaRoute: typeof AuthenticatedAdminCuentaRoute
  AuthenticatedAdminPedidosRoute: typeof AuthenticatedAdminPedidosRoute
  AuthenticatedAdminProductosRoute: typeof AuthenticatedAdminProductosRoute
  AuthenticatedAdminStockFundasRoute: typeof AuthenticatedAdminStockFundasRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAjustesRoute: AuthenticatedAdminAjustesRoute,
  AuthenticatedAdminCarruselRoute: AuthenticatedAdminCarruselRoute,
  AuthenticatedAdminCategoriasRoute: AuthenticatedAdminCategoriasRoute,
  AuthenticatedAdminContenidoRoute: AuthenticatedAdminContenidoRoute,
  AuthenticatedAdminCuentaRoute: AuthenticatedAdminCuentaRoute,
  AuthenticatedAdminPedidosRoute: AuthenticatedAdminPedidosRoute,
  AuthenticatedAdminProductosRoute: AuthenticatedAdminProductosRoute,
  AuthenticatedAdminStockFundasRoute: AuthenticatedAdminStockFundasRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AccesoriosRouteChildren {
  AccesoriosCargadoresRoute: typeof AccesoriosCargadoresRoute
  AccesoriosColgantesRoute: typeof AccesoriosColgantesRoute
  AccesoriosProtectoresRoute: typeof AccesoriosProtectoresRoute
}

const AccesoriosRouteChildren: AccesoriosRouteChildren = {
  AccesoriosCargadoresRoute: AccesoriosCargadoresRoute,
  AccesoriosColgantesRoute: AccesoriosColgantesRoute,
  AccesoriosProtectoresRoute: AccesoriosProtectoresRoute,
}

const AccesoriosRouteWithChildren = AccesoriosRoute._addFileChildren(
  AccesoriosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AccesoriosRoute: AccesoriosRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactoRoute: ContactoRoute,
  FavoritosRoute: FavoritosRoute,
  FundasRoute: FundasRoute,
  FundasMovilRoute: FundasMovilRoute,
  FundasSublimacionRoute: FundasSublimacionRoute,
  MasVendidoRoute: MasVendidoRoute,
  MetaProductsDotcsvRoute: MetaProductsDotcsvRoute,
  MisPedidosRoute: MisPedidosRoute,
  NuevaContrasenaRoute: NuevaContrasenaRoute,
  PersonalizarRoute: PersonalizarRoute,
  PrivacidadRoute: PrivacidadRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TerminosRoute: TerminosRoute,
  TiendaRoute: TiendaRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
  CheckoutExitoRoute: CheckoutExitoRoute,
  ProductHandleRoute: ProductHandleRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
